name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches:
    - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.8', '3.9']
        toxenv: ['py']

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install setuptools wheel tox
        pip install .

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox -- --hypothesis-profile=ci
